### ISSUE TITLE
Incorrect date in notification

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#1789] opened 2023-11-28 17:39 UTC
### Problem

![nov0](https://github.com/okTurtles/group-income/assets/13082264/142cf605-e040-45de-b80a-38bc1e40859a)

Notification is dated "Nov 0", which isn't a correct date. Notification was received on 26 November and there's clearly enough space for a second number character, so doesn't appear to be an issue of truncation/overflow/etc.

This is on Firefox.

### Solution

1. Determine what's causing the issue.
2. Fix it.

**Comment by snowteamer** [comment] 2023-12-30 11:05
It looks like this issue was caused by the `2` character being incorrectly replaced by a non-breaking space, instead of replacing the plain white space.

So in this case, the intended display was likely `Nov 20`.

**Comment by taoeffect** [comment] 2024-01-11 18:13
@snowteamer I merged your PR #1802 but I'm not convinced that it would fix this issue.

Read what @dotmacro wrote:

> So in this case, the intended display was likely Nov 20

This issue was never properly reproduced, there are no steps to reproduce it, and according to her comments this doesn't seem related to non-breaking spaces.

**Comment by taoeffect** [comment] 2024-01-11 19:42
It seems like the notification date might be based on when it was sent, not received, so I'll close this but if it happens again @dotmacro let us know and feel free to re-open!

**Closed as completed by taoeffect** 2024-01-11 19:42 UTC
Labels: Kind:Bug, App:Frontend
