### ISSUE TITLE
Dashboard tab Skeleton

### ISSUE THREAD

**Issue by pieer** [okTurtles/group-income#1403] opened 2022-09-09 20:28 UTC
### Problem

At the moment there is no interface to display all the different user activities and inactivities

### Solution

Implement design solution found in "Design for displaying inactive users [#1332](https://github.com/okTurtles/group-income/issues/1332)" and "Need a design to show percentage of TODOs that were actually completed in Support History [#1286](https://github.com/okTurtles/group-income/issues/1286)"

**Comment by taoeffect** [comment] 2022-12-04 03:23
Think this was either closed or a duplicate of #1449

**Closed as completed by taoeffect** 2022-12-04 03:23 UTC
Labels: Kind:Enhancement, App:Frontend, Priority:High, Note:UI/UX
