### ISSUE TITLE
Cannot add more than one account per payment method

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#915] opened 2020-05-07 03:06 UTC
### Problem

When adding information for multiple accounts using the same payment method, only the last account is saved. This is a problem because the app loses information without informing the user.

1. Go to "Income Details", add multiple accounts for the same payment method (e.g. PayPal) and click save.

<img width="558" alt="3 PayPal Accounts" src="https://user-images.githubusercontent.com/13082264/81250036-dfdf1800-8fd4-11ea-8d0b-9a47fe0ba0d6.png">

2. No error or alert is shown.
3. Re-open Income Details, to see only the last "PayPal" payment was saved.

<img width="569" alt="1 PayPal Saved" src="https://user-images.githubusercontent.com/13082264/81250078-f38a7e80-8fd4-11ea-93c6-a40253c60023.png">

(Note: This does not affect the "other" payment method.)

### Solution

Two possible solutions: 

1. Support adding multiple accounts for the same payment method, because users may have multiple accounts or the platform might support multiple ways of identifying the account (e.g. PayPal email & link).

2. Show the user an error/alert indicating that only one account per method can be saved.

**Comment by sandrina-p** [comment] 2020-05-07 20:57
Hey @dotmacro , that exact bug was opened a few days ago #910 and fixed on #912 last night. Now it should support multiple similar payments.

For that reason, I'm closing this issue.

**Comment by taoeffect** [comment] 2020-05-07 21:01
@

**Comment by taoeffect** [comment] 2020-05-07 21:02
@sandrina-p I think this bug still exists but in a different way, for payments that have the same info for the pre-defined payment types, e.g. PayPal, can you take a closer look?

**Comment by sandrina-p** [comment] 2020-05-07 21:04
I just double-checked with any method name. All of them work fine and are covered with cypress tests.

Next time, please go take a closer look by yourself and verify if the bug you think that exists, really exists. And if yes, describe the steps to reproduce it. This ping-pong of "I think" isn't effective for anyone :)

**Comment by sandrina-p** [comment] 2020-05-07 21:06
Next time, please go take a closer look by yourself and verify if the bug you think that exists, really exists. And if yes, describe the steps to reproduce it. This ping-pong of "I think" isn't much effective for anyone :)

**Comment by taoeffect** [comment] 2020-05-07 21:10
Hmm, I had asked @dotmacro to double-check this last night and she did, and I was convinced she had found a new bug. I just tried it out myself and I'm unable to reproduce it, so I'll go ahead and close this issue.

@dotmacro if you can still reproduce this with latest `master` let us know.

**Closed as completed by taoeffect** 2020-05-07 21:10 UTC
Labels: Kind:Bug, App:Frontend, Priority:Low

**Comment by dotmacro** [comment] 2020-05-09 01:59
Yes, I double-checked and even did a live demo of the bug before opening this issue.

I reproduced the bug again today with c4a9072 (the then-current now-outdated master), but *not* with a872dc4 (current master), so leaving this issue closed.
