### ISSUE TITLE
Broken styles inside Markdown

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1988] opened 2024-05-09 01:02 UTC
### Problem

Writing the following messages would not be rendered correctly, and it looked like its below screenshot.

**[Problem 1.]** Problem with mentions inside the markdown

```
First sentence @andrea 
Second sentence @greg 
Third @alexjin sentence
Fourth Sentence @alexjin @greg @andrea 





Fifth sentence @all @all Sixth sentence @alexjin 
```
![image](https://github.com/okTurtles/group-income/assets/57976479/14a89c8a-2722-4282-ae0f-3494c805a171)

---

**[Problem 2.]** Problem with multiple line breaks
```
First sentence





Second sentence
```
![image](https://github.com/okTurtles/group-income/assets/57976479/be72c76a-e4cd-4817-a2e1-de9c8103b8e0)

---

**[Problem 3.]** Problem with mentions inside the bullets
```
- Drink water: Sometimes thirst can be mistaken for hunger. @alexjin Drinking a glass of water can help you feel full and reduce your appetite.
- Have a small, healthy snack: Choose something from the list we discussed or another healthy option to tide you over until mealtime. @greg - Plan your meal: If you know what you'll be having for your next meal, it can help to distract you from immediate hunger pangs. @andrea 
```
![image](https://github.com/okTurtles/group-income/assets/57976479/15f6f513-5c63-4e46-b480-38a4e1abda5c)

---

### Solution

Fix it

**Comment by SebinSong** [comment] 2024-05-15 23:45
I took some time for investigating this issue and the root cause is,
 **the fact that the message is split into several segments, rather than being treated/rendered as a whole when it contains mentions**.

This is not compatible with using markdown and must be completely changed in order to fix this issue.

e.g.) Let's say below message has been given.

```
- A sentence for a list item @user-1 and another text here
```
Current app logic will look at it and will split this into three segments
which are,
```
<ul><li>A sentence for a list item</li></ul>
<span class='c-mention'>user-1</span>
another text here
```


What if we do the markdown conversion first before splitting the mentions like below?


```
<ul><li>A sentence for a list item @user-1 and another text here</li></ul>
```
Then the current `MessageBase.vue` would slice this into three broken htmls, which is 
```
<ul><li>A sentence for a list item 
<span class='c-mention'>user-1</span>
and another text here</li></ul>
```

So the fix for this would require rather large update on how the `MessageBase.vue` has been working the whole time.

@Silver-IT I will leave this issue assigned to myself for now but go ahead and assign it to yourself and wor when interested, as you seem to be a frequent author of the relevant part of the `MessageBase.vue` component.

cheers,

**Closed as completed** 2024-05-31 03:26 UTC
Labels: Kind:Bug, App:Frontend, Priority:High
