### ISSUE TITLE
File attachment is failed on the first attempt

### ISSUE THREAD

**Issue by Silver-IT** [okTurtles/group-income#1833] opened 2024-02-07 09:08 UTC
### Problem

**Steps to reproduce**
- `u1` signs up, and creates a group
- `u1` goes to the `General` chatroom
- `u1` tries to attach file by clicking the `Attach file` button or dragging the file
- The first attempt would be ignored and nothing would be happening
- `u1` tries to attach file again, then the file would be attached successfully

**What should be happening**
The first attempt should not be ignored, and the file should be attached on the first attempt

### Solution

Fix it

**Comment by SebinSong** [comment] 2024-02-07 21:35
Thanks @Silver-IT for digging out / creating an issue for this bug. I worked on implementing those UI components, so I can pick this one up.

**Comment by Silver-IT** [comment] 2024-02-07 23:58
[File Attachment by Drag&Drop.webm](https://github.com/okTurtles/group-income/assets/57976479/088f836c-2406-48fc-a9c0-1f697b9dda70)

**Comment by taoeffect** [comment] 2024-02-09 16:45
@Silver-IT I also couldn't reproduce this with @SebinSong's PR, so merged and closing.

**Closed as completed** 2024-02-09 16:45 UTC
Labels: Kind:Bug, App:Frontend

**Comment by Silver-IT** [comment] 2024-02-12 07:28
Yeah, Having checked the latest `master` branch after the PR #1834 is merged, I can't reproduce the issue.
Great work, @SebinSong 

cc: @taoeffect
