### ISSUE TITLE
Closed proposals not remaining on dashboard 

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/group-income#1969] opened 2024-04-29 04:45 UTC
### Problem

Dashboard incorrectly says "No one has created a proposal yet." even though a proposal has been created and closed.

![image](https://github.com/okTurtles/group-income/assets/13082264/3a5f87ff-a6a1-4c20-a67b-dc046583d23c)

### Solution

1. The dashboard should no longer say "No one has created a proposal yet" after a proposal has been created.
2. Closed proposals should remain on the dashboard for 24hrs, and then be visible by clicking the "see all proposals" button. 
See note on Figma:  
https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=22920%3A209717&mode=design&t=TQe059xXiCeTqliQ-1

**Comment by SebinSong** [comment] 2024-05-03 02:09
Hi @taoeffect @dotmacro ,
I just spent some time investigating on this issue but haven't been able to reproduce the same issue so far.
(Tried in multiple scenarios of a proposal closing which are `The creator closing it`, `The proposal passed/failed`, `auto-expiration after 2 weeks` using multiple browsers for logging in/out)

Also, it appears that the exact logics taking care of **1.** and **2.** are correctly in place in our proposals widget component ([here](https://github.com/okTurtles/group-income/blob/7368f3f910edbfc105605762fd21c291cdbec9e8/frontend/views/containers/proposals/ProposalsWidget.vue#L169C1-L185C7) cc. @taoeffect ) and it worked properly too.

I guess that could have been a temporary DB-related problem on @dotmacro 's computer because if those archived proposal data were somehow lost or were not able to be loaded from the DB, then the UI would falsely say "No one has created ..." message.

Thanks,

**Comment by taoeffect** [comment] 2024-05-03 03:42
Yeah it's unclear what happened here :-\

@dotmacro if you come across this again let us know. One thing you can do is try creating other groups on the server with fake accounts and creating proposals and seeing what happens. If you're able to reproduce again let us know, and pay special note to any steps you took.

**Comment by dotmacro** [comment] 2024-05-03 12:49
> I guess that could have been a temporary DB-related problem on @dotmacro 's computer because if those archived proposal data were somehow lost or were not able to be loaded from the DB, then the UI would falsely say "No one has created ..." message.

It has been more than a week in real time (i.e. not messing with the system clock), and the dashboard UI still shows the same "No one has created a proposal yet" as in the screenshot [above](https://github.com/okTurtles/group-income/issues/1969#issue-2268111357) even after re-sync, so the problem seems persistent rather than temporary.

The proposal must be in the DB somewhere because it does appear when clicking the "Archived Proposals" button. (But if the user is told "no one has created a proposal yet", how would they know to click to view seemingly non-existent archived proposals?)

If I can reproduce in another group, I'll add additional info.

**Comment by taoeffect** [comment] 2024-05-03 15:42
> "No one has created a proposal yet" as in the screenshot https://github.com/okTurtles/group-income/issues/1969#issue-2268111357 even after re-sync, so the problem seems persistent rather than temporary.

Well, that part isn't a bug. I see the same thing, and it's supposed to say that when there are no open proposals.

> The proposal must be in the DB somewhere because it does appear when clicking the "Archived Proposals" button. (But if the user is told "no one has created a proposal yet", how would they know to click to view seemingly non-existent archived proposals?)

It sounds then more like you're requesting for the text to be different. How about "There are no open proposals." ?

**Comment by SebinSong** [comment] 2024-05-04 02:01
@taoeffect , @dotmacro 
Now I am actually able to reproduce what @dotmacro described as an issue **1.**

I created a proposal and closed it and wait until it's archived(which is 24hr later since its closure).
I can see that the archived item is correctly in place in the `Archived proposals` modal.

<img src='https://github.com/okTurtles/group-income/assets/17641213/eaf763d0-3748-4e77-a0ea-3519514e3df3' width='420'>

But the proposal widget still says No one has created one yet.

<img src='https://github.com/okTurtles/group-income/assets/17641213/c3b97bf6-473b-4802-a433-f0ea7cc308db' width='420'>

If this is something to fix here, I can send a PR for hiding this message when archived proposals are there. 
Does it sound good?

(it still appears the logic regarding **2.** works properly though)

Thnx,

**Comment by SebinSong** [comment] 2024-05-04 02:07
@taoeffect I actually saw [this comment ](https://github.com/okTurtles/group-income/issues/1969#issuecomment-2093267935)of yours late.

So would you want to update the message to say 'There are no **open** proposals' instead? (Which I think sounds good as it covers both cases of "there hasn't been a proposal created at all" / "A group has archived proposals data but no open proposal at a point in time")
Or should we just not consider the description **1.** as a bug as you mentioned?

cc. @dotmacro

**Comment by taoeffect** [comment] 2024-05-04 02:29
> So would you want to update the message to say 'There are no open proposals' instead?

Yes 👍

**Comment by dotmacro** [comment] 2024-05-05 04:44
> Well, that part isn't a bug. I see the same thing, and it's supposed to say that when there are no open proposals.
> It sounds then more like you're requesting for the text to be different. How about "There are no open proposals." ?

Oh! The text was so clear to me that it didn't occur to me that the text needed to be revised (rather than it being a bug, as I reported), or I would have suggested that on Figma before designs were finalized. Sorry!

Yes, I agree it should say "There are no open proposals" instead.

**Closed as completed** 2024-05-07 16:58 UTC
Labels: Kind:Bug, App:Frontend, Note:UI/UX
