### ISSUE TITLE
Update Font Awesome to v5

### ISSUE THREAD

**Issue by sandrina-p** [okTurtles/group-income#491] opened 2018-10-20 09:16 UTC
# Problem
FontAwesome current version is 5 that has new and refined icons much better than the previous version 4.7.0.

Here are some icons examples from one version to another that used at GI:

![image](https://user-images.githubusercontent.com/14869087/47253846-2c91eb00-d451-11e8-8c6c-ef934118c7b6.png)

# Solution
Update Font Awesome to v5. There's a [migration guide](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4) for it.

**Comment by simonv3** [comment] 2018-11-23 18:31
I've put in the work that gets font-awesome working (still probably need to update some of the icons), but wanted to get people's initial take on it:

https://github.com/okTurtles/group-income-simple/compare/master...simonv3:task/fontawesome-5.0?expand=1

Some questions I have:

1. Should we reference the fonts in our own assets folder, or the ones in node modules?
2. Installing font awesome also massively updated the package-lock.json. Do we want to include that update?
3. Right now I'm importing "regular" and "solid" in `main.scss` which I feel are badly namespaced. Any thoughts here? They're declared that way in the relevant `node_modules` folder in font-awesome's scss folder.

Next is going through all the icons and updating them, but I forgot my password, or rather the back-end is throwing an error with what I thought was my password, so will need some help here.

**Comment by taoeffect** [comment] 2018-11-23 21:17
> Should we reference the fonts in our own assets folder, or the ones in node modules?

What do you mean?

The one in `node_modules` should only ever be referenced by the sass compiler. `node_modules` is not accessible via the server. Only the stuff in `dist/` is accessible (see how the Gruntfile copies things into there).

> Installing font awesome also massively updated the package-lock.json. Do we want to include that update?

I'm curious what this `@fortawesome` package is. Why are you not just bumping the version for the existing package we're using? Is it an official repo? (Link to more info of where this came from?)

Re package-lock, to answer that it would help to know the answers to ☝️ 

> Right now I'm importing "regular" and "solid" in main.scss which I feel are badly namespaced. Any thoughts here? They're declared that way in the relevant node_modules folder in font-awesome's scss folder.

The only thoughts I have is only include the absolute minimum necessary. We are not using "regular" (and only "solid"), don't include regular (or comment it out appropriately).

> but I forgot my password, or rather the back-end is throwing an error with what I thought was my password, so will need some help here.

Explained on Slack. Also I will create a documentation issue to explain this in [`Troubleshooting.md`](https://github.com/okTurtles/group-income-simple/blob/master/docs/Troubleshooting.md). (Edit: created #505)

**Comment by simonv3** [comment] 2018-11-23 21:30
> I'm curious what this `@fortawesome` package is. Why are you not just bumping the version for the existing package we're using? Is it an official repo? (Link to more info of where this came from?)

My impression is that font awesome did a bit of an overhaul for 5.x.x, and it's changed its package stuff:

https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-free

I think this is because where everything font awesome < 4.x was free, they want people to pay for font awesome pro etc, so they've had to change their package structure, but that's just speculation. I find their website pretty badly laid out to be honest, but my takeaway - new package location. Doing a simple version bump has npm tell me that it's not available. 

> The one in node_modules should only ever be referenced by the sass compiler. node_modules is not accessible via the server. Only the stuff in dist/ is accessible (see how the Gruntfile copies things into there).

Sorry, yeah, that question wasn't clear. The Font Awesome package comes with the relevant font files. Currently we have those font files manually copied over to our own `assets` folder (e.g. [here](https://github.com/okTurtles/group-income-simple/compare/master...simonv3:task/fontawesome-5.0?expand=1#diff-35bc9794665bcbc33778270c1eeb1314)), rather than referencing the ones in the package manager. As a result, if we were to bump the font awesome version in the future, we'll have to copy those files again. The current way works, but I was wondering if instead we wanted to update the build script to also grab the font awesome fonts from `node_modules` and copy those to the `assets/fonts` folder during build. I'm fine either way, just wanted to know what your preference was. 

> The only thoughts I have is only include the absolute minimum necessary. We are not using "regular" (and only "solid"), don't include regular (or comment it out appropriately).

Sounds good!

**Comment by taoeffect** [comment] 2018-11-23 21:39
OK, then re `package-lock.json` update... question: did doing `npm install` during setup of a clean fresh repo change the `package-lock.json` file? If it *did not*, it means that things are "OK", and then there shouldn't be an issue with sending in a new updated version.

If doing `npm install` on a fresh clone *did* modify `package-lock.json`, it means there's some sort of issue that we need to figure out first.

> The current way works, but I was wondering if instead we wanted to update the build script to also grab the font awesome fonts from node_modules and copy those to the assets/fonts folder during build.

That sounds like a good idea. 👍 

I would recommending trying with just creating a simple symlink using `ln -s` command and seeing if `grunt-contrib-copy` copies over the files by traversing the symlink. If it doesn't, you may need to update the `grunt-contrib-copy` config in the Gruntfile to follow symlinks. And if there is no setting to do that then we need to use some other copy command.

**Comment by simonv3** [comment] 2018-11-24 00:51
> OK, then re package-lock.json update... question: did doing npm install during setup of a clean fresh repo change the package-lock.json file? If it did not, it means that things are "OK", and then there shouldn't be an issue with sending in a new updated version.
> 
> If doing npm install on a fresh clone did modify package-lock.json, it means there's some sort of issue that we need to figure out first.

I wasn't sure what had originally created the package-lock.json, so I created a new clone of the repo and did `npm install`. It _did_ create a new package-lock.json, which is diffed like so: 

https://pastebin.com/bwPbNbwt

For now I'll leave it un-committed. Should I create a new issue to track it if it's a problem?

**Comment by taoeffect** [comment] 2018-11-25 21:17
@simonv3 

> For now I'll leave it un-committed. Should I create a new issue to track it if it's a problem?

I just did a fresh clone + `npm install` of the repo and it did not result in any modifications to the working directory.

This strongly suggests the problem is on your side.

Are you running the latest versions of both npm and nodejs? Make sure you are. You can share the output of `npm version` with me on Slack.

**Comment by taoeffect** [comment] 2018-11-27 00:14
> For now I'll leave it un-committed. Should I create a new issue to track it if it's a problem?

Addressed on this morning's call.

**Comment by simonv3** [comment] 2018-11-27 17:37
Just to conclude: with a new version of node and nvm the package-lock keeps the same versions but adds `optional: true` for some of the packages referenced. This is a linux thing looks like?

**Comment by taoeffect** [comment] 2018-11-28 00:13
@simonv3 Yeah there is some sort of incompatibility between mac and linux npm. See my comment on the PR

**Comment by taoeffect** [comment] 2018-11-28 03:14
Awesome! Closed by @simonv3 in #507, great job on your first PR! 🎉 

Also great job on finding [finding the solution to that package-lock.json optional issue](https://github.com/okTurtles/group-income-simple/pull/507#discussion_r236920724), copied here for reference:

> I removed package-lock.json and ran `npm install --no-optional` as suggested by some folks in that thread. That still creates the necessary bit in package-lock for font-awesome looks like, and removes the optional tags. Seems much cleaner for me to remember the `no-optional` tag the few times we install new dependencies than to constantly have to look at this.

**Closed as completed by taoeffect** 2018-11-28 03:14 UTC
Labels: App:Frontend, Note:Tooling, Note:UI/UX
